export const PRESTAMO = {
  SUBMIT: 'PRESTAMO/SUBMIT',
  CANCEL: 'PRESTAMO/CANCEL'
};

export const COUNTER = {
  INCREMENT: 'COUNTER/INCREMENT',
  DECREMENT: 'COUNTER/DECREMENT'
};

export const CUSTOMER = {
  GET: 'CUSTOMER/GET',
  CREATE: 'CUSTOMER/CREATE',
  UPDATE: 'CUSTOMER/UPDATE',
  DELETE: 'CUSTOMER/DELETE',
  SELECT: 'CUSTOMER/SELECT'
};
